name: Release
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            name: linux64
            asset_name: keepsorted-linux64
          - os: macos-12
            name: macos
            asset_name: keepsorted-macos

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --release --all-targets

      - name: Prepare Release Binary
        run: |
          mkdir -p release
          cp target/release/keepsorted release/${{ matrix.asset_name }}
          tar -czvf keepsorted-${{ matrix.asset_name }}.tar.gz -C release keepsorted-${{ matrix.asset_name }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./keepsorted-${{ matrix.asset_name }}.tar.gz
          asset_name: keepsorted-${{ matrix.asset_name }}.tar.gz
          asset_content_type: application/gzip
